spring:
  datasource:
    url: jdbc:sqlserver://dbhackathon.database.windows.net;databaseName=hack
    username: hack
    password: Password23
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    path: /