spring:
  datasource:
    url: jdbc:sqlserver://dbhackathon.database.windows.net;databaseName=hack
    username: hack
    password: Password23
  jpa:
    show-sql: false

springdoc:
  swagger-ui:
    path: /

event-hub:
  namespace: eventhack.servicebus.windows.net
  key-name: hack
  key-value: HeHeVaVqyVkntO2FnjQcs2Ilh/4MUDo4y+AEhKp8z+g=
  name: simulacoes